version: "3.8"

services:
  mariadb:
    build: ./requirements/mariaDB
    networks:
      - inception
    env_file:
      - .env
    restart: always
    volumes:
      - vol_mariadb:/var/lib/mysql

  nginx:
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - vol_wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always

  wordpress:
    build: ./requirements/wordpress
    networks:
      - inception
    env_file:
      - ./.env
    volumes:
      - vol_wordpress:/var/www/html
    depends_on:
      - mariadb
    restart: always
  web:
      build: ./bonus/web
      ports:
        - 8081:8081
      restart: always
  adminer:
      build: ./bonus/adminer
      networks:
        - inception
      ports:
        - 8080:8080
      restart: always

networks:
  inception:
    driver: bridge

volumes:
  vol_wordpress:
    name: v_wordpress
    driver: local
    driver_opts:
      device: /Users/hchahid/Desktop/data/vol_wordpress
      type: none
      o: bind
  vol_mariadb:
    name: v_mariadb
    driver: local
    driver_opts:
      device: /Users/hchahid/Desktop/data/vol_mariadb
      type: none
      o: bind